name: Integration Tests
on: [pull_request]

jobs:
  tutor-integration-test:
    name: Integration with Tutor
    strategy:
      matrix:
        tutor_version: ["<19.0.0", "<18.0.0"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare Tutor & launch
        run: |
          pip install "tutor${{ matrix.tutor_version }}"
          pip install -e .
          TUTOR_ROOT="$(pwd)" tutor --version
          TUTOR_ROOT="$(pwd)" tutor config save

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Enable the tutor plugin
        run: |
          TUTOR_ROOT="$(pwd)" tutor plugins enable picasso
          TUTOR_ROOT="$(pwd)" tutor picasso -h

      - name: Adding data to the config.yml
        run: |
          TUTOR_VERSION=$(tutor --version | awk '{print $NF}')
          cat <<EOF >> config.yml
          TUTOR_VERSION: $TUTOR_VERSION
          PICASSO_MANAGE_DPKG:
            name: eox-manage
            repo: git@github.com:eduNEXT/eox-manage.git
            version: v6.1.0
          PICASSO_THEMES:
            - name: endx-saas-themes
              repo: git@github.com:eduNEXT/ednx-saas-themes.git
              version: master
          PICASSO_THEME_DIRS:
          - /openedx/themes/ednx-saas-themes/edx-platform
          - /openedx/themes/ednx-saas-themes/edx-platform/bragi-generator
          - /openedx/themes/ednx-saas-themes/edx-platform/bragi-children
          PICASSO_THEMES_NAME:
          - bragi
          - css-runtime
          PICASSO_EXTRA_COMMANDS:
            - tutor plugins update
            - tutor plugins index add https://raw.githubusercontent.com/eduNEXT/tutor-plugin-indexes/picasso_test/
            - tutor plugins install mfe mfe_extensions aspects
            - tutor plugins enable mfe mfe_extensions aspects
            - tutor plugins list | tutor config save
          EOF

      - name: Check run-extra-commands
        run: |
          TUTOR_ROOT="$(pwd)" tutor picasso run-extra-commands

      - name: Check enable-themes
        run: |
          TUTOR_ROOT="$(pwd)" tutor picasso enable-themes

          if grep -q 'bragi' env/build/openedx/Dockerfile; then
            echo "'bragi' found in env/build/openedx/Dockerfile."
          else
            echo "'bragi' not found for the building process."
            exit 1
          fi

          if grep -q '/openedx/themes/ednx-saas-themes/edx-platform' env/build/openedx/Dockerfile; then
            echo "'/openedx/themes/ednx-saas-themes/edx-platform' found in env/build/openedx/Dockerfile."
          else
            echo "'/openedx/themes/ednx-saas-themes/edx-platform' not found for the building process."
            exit 1
          fi

          if grep -q 'ENABLE_COMPREHENSIVE_THEMING = True' env/apps/openedx/settings/lms/production.py; then
            echo "'ENABLE_COMPREHENSIVE_THEMING = True' found in env/apps/openedx/settings/lms/production.py."
          else
            echo "'ENABLE_COMPREHENSIVE_THEMING = True' not found in env/apps/openedx/settings/lms/production.py."
            exit 1
          fi

      - name: Check enable-private-packages
        run: |
          TUTOR_ROOT="$(pwd)" tutor picasso enable-private-packages

          if grep -q 'eox-manage' env/build/openedx/requirements/private.txt; then
            echo "'eox-manage' found in env/build/openedx/requirements/private.txt."
          elif grep -q 'eox-manage' env/build/openedx/Dockerfile; then
            echo "'eox-manage' found in env/build/openedx/Dockerfile."
          else
            echo "'eox-manage' not found for the building process."
            exit 1
          fi
